### ISSUE TITLE
Can't make pen disable touch

### ISSUE THREAD

**Issue by ardynn** [morrolinux/SurfaceLinuxGoodies#3]
I'm still not proficient in Linux, so forgive me if I'm asking a really basic question.

I've copied pen-disable-touch.service and pen-disable-touch.sh to the right locations. I tried to enable to service with: 

`sudo systemctl start /usr/lib/systemd/system/pen-disable-touch.service`

I get the error:

`Failed to start usr-lib-systemd-system-pen\x2ddisable\x2dtouch.service.mount: Unit usr-lib-systemd-system-pen\x2ddisable\x2dtouch.service.mount not found.`

I've had a look in both files, but I can't find any reference to x2dtouch.service.mount.

Any help would be much appreciated.

**Comment by morrolinux** [comment]
After you copied `pen-disable-touch.service` to `/usr/lib/systemd/system` you enable the service with `systemctl enable pen-disable-touch.service` (without the path) and you can start it with `systemctl start pen-disable-touch.service` 
BTW It's only tested to be working on a surface pro 3 running on xorg. If you have a different tablet or software configurations, adjustments may be needed
